# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
