# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
