# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170507_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/')),
                ('image_title', models.CharField(max_length=200)),
                ('image_author', models.CharField(max_length=150)),
                ('image_description', models.CharField(blank=True, max_length=250)),
                ('image_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
